server:
  port: 8091
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:sqlserver://210.22.183.72:1433;databaseName=KoreaComment
    username: sa
    password: Datamining2014
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialSize: 15
    minIdle: 10
    maxActive: 20
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM korea_comments_target_brands
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    logSlowSql: true
  jpa:
    database: sql_server
    #    show-sql: true
    hibernate:
      #      ddl-auto : update
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #    org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

      #    properties:
      #      hibernate:
      #        dialect : org.hibernate.dialect
  task:
    pool:
      corePoolSize: 50
      maxPoolSize: 60
      keepAliveSeconds: 60
      queueCapacity: 50
